import type { UnitType } from 'sim/types';

export const UNIT_TYPES: UnitType[] = [
  {
    id: 'levy-t1',
    name: 'Levy',
    tier: 1,
    domain: 'land',
    role: 'infantry',
    combatValue: 5,
    baseSpeedKmh: 5,
    fundingCost: 200,
    manpowerCost: 300,
    buildHours: 12,
    billOfMaterials: { food: 15 },
  },
  {
    id: 'infantry-t2',
    name: 'Infantry',
    tier: 2,
    domain: 'land',
    role: 'infantry',
    combatValue: 10,
    baseSpeedKmh: 5,
    fundingCost: 800,
    manpowerCost: 500,
    buildHours: 24,
    billOfMaterials: { steel: 30, food: 20 },
  },
  {
    id: 'riflemen-t3',
    name: 'Riflemen',
    tier: 3,
    domain: 'land',
    role: 'infantry',
    combatValue: 25,
    baseSpeedKmh: 6,
    fundingCost: 2500,
    manpowerCost: 400,
    buildHours: 36,
    billOfMaterials: { steel: 50 },
  },
  {
    id: 'mg-armor-t5',
    name: 'MG + Armor',
    tier: 5,
    domain: 'land',
    role: 'armor',
    combatValue: 80,
    baseSpeedKmh: 40,
    fundingCost: 8000,
    manpowerCost: 150,
    buildHours: 72,
    billOfMaterials: { steel: 200, fuel: 100 },
  },
  {
    id: 'scout-t1',
    name: 'Scout',
    tier: 1,
    domain: 'land',
    role: 'spy',
    // Combat weight applied via SCOUT_COMBAT_WEIGHT_MULT in sim/scout.ts
    combatValue: 5,
    baseSpeedKmh: 6,
    // 50% of infantry-t2 (800) — see SCOUT_BUILD_COST_MULT in sim/scout.ts
    fundingCost: 400,
    manpowerCost: 200,
    buildHours: 18,
    billOfMaterials: { food: 10 },
  },
  {
    id: 'destroyer-t2',
    name: 'Destroyer',
    tier: 2,
    domain: 'sea',
    role: 'naval',
    combatValue: 30,
    baseSpeedKmh: 55,
    fundingCost: 8000,
    manpowerCost: 150,
    buildHours: 72,
    billOfMaterials: { steel: 300, rareMetals: 50 },
  },
];

export const UNIT_TYPES_BY_ID: Record<string, UnitType> = Object.fromEntries(
  UNIT_TYPES.map((u) => [u.id, u]),
);
